package com.zdevtest.betadb.txmapper;

import com.zdevtest.betadb.txmodel.ZaWeblog;
import com.zdevtest.betadb.txmodel.ZaWeblogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ZaWeblogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table za_weblog
     *
     * @mbggenerated
     */
    int countByExample(ZaWeblogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table za_weblog
     *
     * @mbggenerated
     */
    int deleteByExample(ZaWeblogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table za_weblog
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer zid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table za_weblog
     *
     * @mbggenerated
     */
    int insert(ZaWeblog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table za_weblog
     *
     * @mbggenerated
     */
    int insertSelective(ZaWeblog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table za_weblog
     *
     * @mbggenerated
     */
    List<ZaWeblog> selectByExample(ZaWeblogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table za_weblog
     *
     * @mbggenerated
     */
    ZaWeblog selectByPrimaryKey(Integer zid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table za_weblog
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ZaWeblog record, @Param("example") ZaWeblogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table za_weblog
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ZaWeblog record, @Param("example") ZaWeblogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table za_weblog
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ZaWeblog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table za_weblog
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ZaWeblog record);
}