package com.zdevtest.betadb.txmodel;

public class ZaWeblog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column za_weblog.zid
     *
     * @mbggenerated
     */
    private Integer zid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column za_weblog.uid
     *
     * @mbggenerated
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column za_weblog.log_type
     *
     * @mbggenerated
     */
    private String logType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column za_weblog.log_title
     *
     * @mbggenerated
     */
    private String logTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column za_weblog.log_content
     *
     * @mbggenerated
     */
    private String logContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column za_weblog.create_time
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column za_weblog.zid
     *
     * @return the value of za_weblog.zid
     *
     * @mbggenerated
     */
    public Integer getZid() {
        return zid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column za_weblog.zid
     *
     * @param zid the value for za_weblog.zid
     *
     * @mbggenerated
     */
    public void setZid(Integer zid) {
        this.zid = zid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column za_weblog.uid
     *
     * @return the value of za_weblog.uid
     *
     * @mbggenerated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column za_weblog.uid
     *
     * @param uid the value for za_weblog.uid
     *
     * @mbggenerated
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column za_weblog.log_type
     *
     * @return the value of za_weblog.log_type
     *
     * @mbggenerated
     */
    public String getLogType() {
        return logType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column za_weblog.log_type
     *
     * @param logType the value for za_weblog.log_type
     *
     * @mbggenerated
     */
    public void setLogType(String logType) {
        this.logType = logType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column za_weblog.log_title
     *
     * @return the value of za_weblog.log_title
     *
     * @mbggenerated
     */
    public String getLogTitle() {
        return logTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column za_weblog.log_title
     *
     * @param logTitle the value for za_weblog.log_title
     *
     * @mbggenerated
     */
    public void setLogTitle(String logTitle) {
        this.logTitle = logTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column za_weblog.log_content
     *
     * @return the value of za_weblog.log_content
     *
     * @mbggenerated
     */
    public String getLogContent() {
        return logContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column za_weblog.log_content
     *
     * @param logContent the value for za_weblog.log_content
     *
     * @mbggenerated
     */
    public void setLogContent(String logContent) {
        this.logContent = logContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column za_weblog.create_time
     *
     * @return the value of za_weblog.create_time
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column za_weblog.create_time
     *
     * @param createTime the value for za_weblog.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }
}